USE POS;

INSERT INTO POS.CLIENTE(ID_CLIENTE, NOMBRE, APELLIDO, NIT, DIRECCION, TELEFONO) VALUES('1', 'Ronald', 'Galicia', '88007995', 'Guatemala', '5555-5555');
INSERT INTO POS.CLIENTE(ID_CLIENTE, NOMBRE, APELLIDO, NIT, DIRECCION, TELEFONO) VALUES('2', 'Karla', 'Navarro', '9985004', 'Guatemala', '4433-2211');
INSERT INTO POS.CLIENTE(ID_CLIENTE, NOMBRE, APELLIDO, NIT, DIRECCION, TELEFONO) VALUES('3', 'Karla', 'Navarro', '9985004', 'Guatemala', '4433-2211');

SELECT * FROM POS.CLIENTE;

UPDATE
	POS.CLIENTE
SET
	NOMBRE = 'Kisha', APELLIDO = 'Salazar',
	NIT = '44553342', DIRECCION = 'Guatemala', 
	TELEFONO = '43566773'
WHERE
	POS.CLIENTE.ID_CLIENTE = 2;

DELETE FROM 
	POS.CLIENTE
WHERE 
	POS.CLIENTE.ID_CLIENTE = 3;
