


use POS

SELECT * FROM POS.TIPO_PRODUCTO
SELECT * FROM POS.PRODUCTO

INSERT INTO POS.PRODUCTO(ID_PRODUCTO, ID_TIPO_PRODUCTO,DESCRIPCION,PRECIO,EXISTENCIA,ESTADO) VALUES ('1','1','CLORO',25,100,1)

INSERT INTO POS.PRODUCTO(ID_PRODUCTO, ID_TIPO_PRODUCTO,DESCRIPCION,PRECIO,EXISTENCIA,ESTADO) VALUES ('2','2','CEREAL',20,50,1)

INSERT INTO POS.PRODUCTO(ID_PRODUCTO, ID_TIPO_PRODUCTO,DESCRIPCION,PRECIO,EXISTENCIA,ESTADO) VALUES ('3','2','LECHE',10,150,1)

UPDATE 
	POS.PRODUCTO
SET 
	DESCRIPCION = 'ASISTIN',
	PRECIO = 2,
	EXISTENCIA = 75,
	ESTADO = 1
WHERE 
	POS.PRODUCTO.ID_PRODUCTO =1;


DELETE FROM
POS.PRODUCTO

WHERE 
POS.PRODUCTO.ID_PRODUCTO = 1;