USE POS;

/*roles {CRUD} */

INSERT INTO SEG.ROL(ID_ROL, DESCRIPCION ) VALUES('1', 'admin');
INSERT INTO SEG.ROL(ID_ROL, DESCRIPCION ) VALUES('2', 'normal');
INSERT INTO SEG.ROL(ID_ROL, DESCRIPCION ) VALUES('4', 'reporteria');

SELECT * FROM SEG.ROL;

UPDATE 
	SEG.ROL 
SET 
	DESCRIPCION  = 'admin' 
WHERE 
	SEG.ROL.ID_ROL = 1;


DELETE FROM 
	SEG.ROL 
WHERE 
	SEG.ROL.ID_ROL = 4;


/*usuarios {CRUD} */

INSERT INTO SEG.USUARIO( ID_USUARIO, NOMBRE, APELLIDO, USUARIO,CLAVE, ID_ROL, ESTADO ) VALUES(4, 'pablo', 'jacobo', 'hackobo', CAST('123abC' AS VARBINARY(MAX)), 2, 1 );

SELECT * FROM SEG.USUARIO;

UPDATE 
	SEG.USUARIO 
SET 
	NOMBRE = 'Pablo', APELLIDO = 'Jacobo', 
	USUARIO = 'hackb', CLAVE = CAST('XDDASES' AS VARBINARY(MAX)), 
	ID_ROL = 1, ESTADO = 0
WHERE
	SEG.USUARIO.ID_USUARIO = 1;

DELETE FROM SEG.USUARIO WHERE ID_USUARIO = 4;